POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFudHRpIiwiaWQiOiI1YzZhYTNjOWJmNWU2ZDM0MzM4ZTlhNjEiLCJpYXQiOjE1NTA1MDk2MjV9.lf2-nhTevv8kqjyDvde0r1mjICQDjCGAHZeVmd8ch9M

{
  "title": "Antin vanha blogi",
  "author": "Antti",
  "url": "antinblogi.fi",
  "likes": 7
}
